### ISSUE TITLE
Not working with sketch update 66.1

### ISSUE THREAD

**Issue by nbrustein** [heytitle/latex-sketch-plugin#7]
As of sketch update 66.1, the plugin opens, but when you click ‘Insert’ nothing happens.

**Comment by royalcleanindia** [comment]
> As of sketch update 66.1, the plugin opens, but when you click ‘Insert’ nothing happens.

@heytitle, is there any update available in near future for this issue?
Thank you.

**Comment by heytitle** [comment]
Sry for my late reply! I'll take a look at it this weekend.

**Comment by heytitle** [comment]
I've looked into the problem. It turns out that Sketch obsoleted its v1 api, which I used in the plugin. So, it seems not an easy fix.

**Comment by royalcleanindia** [comment]
> I've looked into the problem. It turns out that Sketch obsoleted its v1 api, which I used in the plugin. So, it seems not an easy fix.

Thanks for your reply. I reinstalled Sketch version 65 (along with the 66.1) to use the latex sketch plugin. I hope we will get a fix in the future. Thanks again for your amazing work.

**Comment by heytitle** [comment]
@royalcleanindia @nbrustein I've made the plugin compatible with Sketch 66.11.

Please check: https://github.com/heytitle/latex-sketch-plugin/releases/tag/v7.0.0.

Quick question: I haven't implemented the edit functionality yet, and I personally rarely used it. Do you think we should have it?

**Comment by royalcleanindia** [comment]
@heytitl, thank you very much!

Plugin is working fine with Sketch Version 66.1 (97080).

I am not using 'edit' functionality. As at the time of insert, I can check the output in the preview. So there are rare chances to make a mistake. I feel we do not need this 'edit' functionality at the moment. 

In the future, if you have time, please add it again as sometimes it may be easy to copy and edit a previous layer for just changing a minimal numeric value (instead of writing from scratch).

**Comment by heytitle** [comment]
thanks for the feedback! I'll close this issue for now.
